# Generated by Django 4.2.6 on 2024-08-07 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='recipe_desp',
            new_name='recipe_description',
        ),
    ]
