# Generated by Django 4.2.6 on 2024-08-13 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_subject_subject_marks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subject_marks',
            new_name='Subject_mark',
        ),
    ]
