# Generated by Django 4.2.6 on 2024-08-15 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_subject_marks_subject_mark'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject_mark',
            options={'ordering': ['student']},
        ),
        migrations.CreateModel(
            name='Report_card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_rank', models.IntegerField()),
                ('date_of_generation', models.DateField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentreportcard', to='main.student')),
            ],
            options={
                'unique_together': {('student_rank', 'date_of_generation')},
            },
        ),
    ]
