# Generated by Django 4.2.6 on 2024-08-19 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_subject_mark_options_report_card'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report_card',
            options={'ordering': ['student_rank']},
        ),
    ]
