# Generated by Django 4.2.6 on 2024-08-19 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_report_card_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report_card',
            options={},
        ),
    ]
